Mctalreader removal
JADE-V-V/JADE pull request #300
Opened 2024-06-12 14:54 UTC by AlbertoBittes

# Description

Please include a summary of the changes and the related issue (if applicable). Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

Additional dependencies introduced.
- Dependency 1
- Dependency 2

## Type of change

Please select what type of change this is.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New benchmark
    - [ ] Non-breaking change which entirely uses exisiting classes, structure etc
    - [ ] Breaking change which has implemented new/modified classes etc
- [ ] New feature 
    - [ ] Non-breaking change which adds functionality
    - [ ] Breaking change fix or feature that would cause existing functionality to not work as expected

## Other changes

- [ ] This change requires a documentation update
- [ ] (If Benchmark) This requires additional data that can be obtained from:
    - Benchmark data 1
    - Benchamrk data 2

# Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B
- etc

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] General testing 
    - [ ] New and existing unit tests pass locally with my changes
    - [ ] Coverage is >80%

2024-07-04 14:49 UTC, dodu94 requested changes
Thanks Alberto, good job!

2024-07-04 14:49 UTC, dodu94 commented on docs/source/api/general.rst
Can you please link these to the F4Enix API reference? you can find them navigating here: https://f4enix.readthedocs.io/en/latest/_autosummary/f4enix.input.html#module-f4enix.input

2024-07-04 14:49 UTC, dodu94 commented on docs/source/api/initobjects.rst
Can you double check if these are used anymore? I believe we removed the automatic API generation

2024-07-04 14:49 UTC, dodu94 commented on docs/source/api/inputgeneration.rst
see above comment

2024-07-04 14:49 UTC, dodu94 commented on jade/output.py
Can you explain what is happening here?
```python
self.out.stat_checks = self.out.get_statistical_checks_tfc_bins()
self.out.stat_checks = self.out.assign_tally_description(
    self.out.stat_checks, self.mctal.tallies)
```

why it is overridden?

2024-07-04 14:49 UTC, dodu94 commented on jade/plotter.py
Have you double checked that ```dic["x"]``` is actually what exits from mcnp and was not modified at some point to be the midpoints?

2024-07-04 14:49 UTC, dodu94 commented on jade/sphereoutput.py
1) Why is this needed?

```python
def __init__(self):
    raise RuntimeError("SphereTallyOutput cannot be instantiated")
```

2) ```def _get_tallydata(self, mctal):``` in the ``SphereOutput`` produces a different DataFrame with respect to the one of F4Enix? Do we really need to keep it or we can use that one? Also because now we are reading the tallies twice since this is done also in the ``super().__init__()``

2024-07-04 14:49 UTC, dodu94 commented on jade/testrun.py
It seems that the logic of the D1S translation has been changed here. What JADE did in the past ([here](https://github.com/JADE-V-V/JADE/blob/ccbb1b2916870214e3e889b0da4c7b365b6c1aa4/jade/inputfile.py#L457)) was to take all possible reactions, check which daughters are in the irradiation file and then convert all the parents found in the mcnp input with the activation library, the others with the transport. That is why it was outputting the list of new irradiations and reactions. ``smart_translate()`` ([here](https://f4enix.readthedocs.io/en/latest/_autosummary/f4enix.input.MCNPinput.D1S_Input.html#f4enix.input.MCNPinput.D1S_Input.smart_translate)) checks the reaction file and use the list of reactions there as input to get the parents where activation libraries should be applied in the mcnp input.

In general, in D1S input the irradiation file has to be provided, since time factor cannot be computed by JADE or F4Enix. This means that if you want to keep the same behaviour as before (and we want), first we need to call ``get_reaction_file()`` in order to get all reactions leading to those daughters, and only after that we can call ``smart_translate()``.

Once this is done, I think we can delete also this part of the code:
```python
 newirradiations = []
            available_daughters = self.d1s_inp.irrad_file.get_daughters()
            for reaction in self.d1s_inp.reac_file.reactions:
                if reaction.daughter in available_daughters:
                    # add the correspondent irradiation
                    irr = self.d1s_inp.irrad_file.get_irrad(reaction.daughter)
                    if irr not in newirradiations:
                        newirradiations.append(irr)
            self.irrad.irr_schedules = newirradiations
            self.react.reactions = newreactions

            self.react.reactions = self.d1s_inp.reac_file.reactions
```
please add a suitable test for this. Like for instance checking the ITER cylinder benchmark. The reactions in the react file should depend on the library as the application of the activation lib in the input.

2024-07-15 15:43 UTC, dodu94 approved these changes
Thanks Alberto, all good from my side now. @alexvalentine94 can start his review now.

2024-08-06 07:20 UTC, alexvalentine94 reviewed
Thanks for this great effort. This has made the code base much more concise and a lot neater in parts. I have made some comments, nothing particularly major.

2024-08-06 07:20 UTC, alexvalentine94 commented on docs/source/api/general.rst
> +with d1s code, an irradiation file and a reaction file (`<https://f4enix.readthedocs.io/en/latest/_autosummary/f4enix.input.d1suned.html>`) are also associated with the
link needs to be formatted correctly

2024-08-06 07:20 UTC, alexvalentine94 commented on docs/source/api/general.rst
> +    the Status object has informations on which libraries have
'information'

2024-08-06 07:20 UTC, alexvalentine94 commented on docs/source/usage/utilities.rst
A general point on documentation - As F4Enix is a large dependancy and JADE relies on it now heavily it would be good to have this noted in the introductory sections of the docs. This could go in the 'JADE in a nutshell' for example. Something like 'MCNP input and output handling is performed by F4Enix (link). This package contains a range of utilities for the creation and post-processing of MCNP files.'

2024-08-06 07:20 UTC, alexvalentine94 commented on jade/gui.py
to check - updated/completeness of unit test

2024-08-06 07:20 UTC, alexvalentine94 commented on jade/output.py
> +                    # Create fake tallies to be added to the mctal
Ok better if renamed from 'fake' but I understand the logic

2024-08-06 07:20 UTC, alexvalentine94 commented on jade/sphereoutput.py
I guess SphereTallyOutput is never instantiated on its own, now we are differentiating across codes so makes sense to define it as an abstract class. I think there are neater way to do this however by defining each method as an @abstractmethod. However thiscan be for future polishing.

2024-08-06 07:20 UTC, alexvalentine94 commented on jade/utilitiesgui.py
> +from importlib.resources import files, as_file
as_file is not used

2024-08-06 07:20 UTC, alexvalentine94 commented on jade/utilitiesgui.py
OK - a lot neater now these slightly out of scope utilities are not sat in JADE.

2024-08-06 07:20 UTC, alexvalentine94 commented on tests/computational_test.py
> +            print(lib)
This should be removed

2024-08-06 07:20 UTC, alexvalentine94 commented on tests/computational_test.py
> +def test_select_lib(monkeypatch):
It would be better to separate this in to two separate test functions for test and failure so they can fail independently. It would also be neater to use 'pytest.raises' but to be consistent with the rest of the code, assert statements are OK.

The behaviour for lib selection differs between codes so we should extend the tests to openmc and serpent also. This is something UKAEA can add - issue to be raised.

2024-08-06 07:20 UTC, alexvalentine94 commented on tests/expoutput_test.py
>          assert True
These two tests are quite weak currently as just smoke tests for the functions running. Unless we have some assertions in the methods themselves, they may still be giving incorrect behavior and the test passing. We should elaborate to assert specific outcomes based on actual results.

2024-08-06 07:20 UTC, alexvalentine94 commented on tests/libmanager_test.py
Im assuming library conversion is now tested with F4Enix. As this will be handled separately for openmc and serpent we can perhaps introduce the tests in computational_test.py alongside the other tests you have moved from this file.

2024-08-06 07:20 UTC, alexvalentine94 commented on tests/xsdirpyne_test.py
Again, assuming tests within F4Enix

2024-08-06 07:20 UTC, alexvalentine94 commented on tests/utilitiesgui_test.py
>          assert True
Again, as with other tests, this is not particularly useful. The function print_XS_EXFOR, which by the way is extremely long and should be broken down, returns a figure, a minimum change could be to assert that this file exists.

2024-08-09 12:26 UTC, alexvalentine94 approved these changes
Thanks Alberto for adressing the comments. I am happy with the revisions and that the code is suitable for merging.

2024-08-09 12:26 UTC, merged