Introduce output class using OpenMC API
JADE-V-V/JADE pull request #328
Opened 2024-10-19 11:02 UTC by alexvalentine94

# Description

Introduce output class for openmc using the API. Read code version from statepoint for metadata. 

## Type of change

Please select what type of change this is.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New benchmark
    - [ ] Non-breaking change which entirely uses exisiting classes, structure etc
    - [ ] Breaking change which has implemented new/modified classes etc
- [x] New feature 
    - [x] Non-breaking change which adds functionality
    - [ ] Breaking change fix or feature that would cause existing functionality to not work as expected

# Testing

- Added test to make sure version is read from statepoint correctly with API. 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] General testing 
    - [X] New and existing unit tests pass locally with my changes
    - [ ] Coverage is >80%

2024-10-21 09:39 UTC, alexvalentine94 commented
Look to improve codecov

2024-10-22 08:57 UTC, alexvalentine94 commented
> Look to improve codecov
Changes look to be covered.

2024-10-25 07:56 UTC, dodu94 requested changes
Good work, just have a look at the d1s comments

2024-10-25 07:56 UTC, dodu94 commented on jade/output.py
> +
maybe it worth to add here a NotImplementedError if another code is requested

2024-10-25 07:56 UTC, dodu94 commented on jade/output.py
> +            if code == "mcnp":
this should be valid also for d1s

2024-10-25 07:56 UTC, dodu94 commented on jade/output.py
> +        if file1 is None or (code == "mcnp" and file2 is None):
mcnp and d1s behave in the same way here

2024-10-25 10:54 UTC, alexvalentine94 commented
Thanks Davide, I have implemented the changes as you suggested.

2024-10-25 12:48 UTC, dodu94 approved these changes

2024-10-25 12:48 UTC, merged